version: '3.6'

services:
#  origin:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    restart: always
#    ports:
#    - "1935:1935/tcp"
#    - "8443:8443/tcp"
#    - "9000:9000/tcp"
#    - "9999:9999/udp"
#    environment:
#    - OME_RTMP_PROV_PORT=1935
#    - TLS_HTTP_PORT=8443
#    - OVT_ORIGIN_PORT=9000
#    - OME_SRT_PROV_PORT=9999
#    - TLS_DOMAIN_NAME=sinkx.example.com
#    - CPU_CORES_COUNT=2
#    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf
#    volumes:
#    - ./local-data/origin_conf:/opt/ovenmediaengine/bin/origin_conf
#    - ./local-data/tls:/etc/ssl

  edge:
    image: ome_edge_image:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "80:80/tcp"
    - "443:443/tcp"
    - "3334:3334/tcp"
    - "3479:3479/tcp"
    - "8944:8944/tcp"
    - "9001:9001/tcp"
    - "10000-10005:10000-10005/udp"
    environment:
    - TLS_HTTP_PORT=443
    - OME_SIGNALLING_PORT=3334
    - OME_TCP_RELAY_ADDRESS=123.123.123.123:3479
    - TLS_API_PORT=8944
    - OVT_ORIGIN_PORT=9000
    - OME_ICE_CANDIDATES=123.123.123.123:10000-10005/udp
    - OVT_ORIGIN_SERVER_EU=sink1.example.com
    - OVT_ORIGIN_SERVER_USA=sink2.example.com
    - TLS_DOMAIN_NAME=oven.example.com
    - CPU_CORES_COUNT=2
    - OME_ACCESS_TOKEN=ome-access-token
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf
    volumes:
    - ./local-data/edge_conf:/opt/ovenmediaengine/bin/edge_conf
    - ./local-data/tls:/etc/ssl
